import "./globals.css";
import Layout from "@/components/layout";
import { Instrument_Sans } from "next/font/google";

const InstrumentSans = Instrument_Sans({
  weight: ["400", "500", "600", "700"],
  variable: "--font-instrumental-sans",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${InstrumentSans.className} antialiased`}
        suppressHydrationWarning={true}
      >
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
