export const endpoints = {
  auth: {
    login: "/auth/login",
    logout: "/auth/logout",
    signup: "/auth/signup",
    refresh: "/auth/refresh",
    username: "/auth/username",
  },
  profile: "/users/me",
  users: { getAll: "/users" },
  applications: { getAll: "/applications" },
  companyProfiles: { getAll: "/company-profiles" },
  userKeyContacts: { getAll: "/user-key-contacts" },
  authorities: { getAll: "/authorities" },
  tenders: { getAll: "/tenders" },
  plans: { getAll: "/plans" },
  sectors: { getAll: "/sectors" },
  keywords: { getAll: "/keywords" },
  industries: { getAll: "/industries" },
  states: { getAll: "/states" },
  cities: { getAll: "/cities" },
  files: {
    getFiles: "/upload",
    deleteKey: "/upload/s3",
    preSignedUrl: "/upload/presigned-url",
    preSignedUrls: "/upload/presigned-urls",
  },
};
