import { z } from "zod";

export const TenderSchema = z.object({
  name: z
    .string({ required_error: "Tender name is required!" })
    .min(1, { message: "tender name is required!" }),
  tender_amount: z.number().int().default(0),
  // bid_start_date: z.string(),
  // bid_end_date: z.string(),
  bid_number: z.string().default(""),
  dated: z.string().default(""),
  bid_end_date_time: z.coerce.date(),
  department: z.string().default(""),
  organisation: z.string().default(""),
  office: z.string().default(""),
  item_gem_parts: z.string().default(""),
  quantity: z.string().default(""),
  uom: z.string().default(""),
  no_of_items: z.string().default(""),
  minimum_average_annual_turnover: z.string().default(""),
  years_of_past_experience: z.string().default(""),
  evaluation_method: z.string().default(""),
  emd_amount: z.string().default(""),
  tender_value: z.string().default(""),
  ote_lte: z.string().default(""),
  epbg_percentage: z.string().default(""),
  consignee: z.string().default(""),
  delivery_days: z.string().default(""),
  distribution: z.string().default(""),
  pre_qualification_criteria: z.string().default(""),

  bid_to_ra_enabled: z.boolean().default(false),
  mse_exemption_for_turnover: z.boolean().default(false),
  save_to_my_business: z.boolean().default(false),
  splitting_applied: z.boolean().default(false),
  startup_exemption_for_turnover: z.boolean().default(false),

  authority_ids: z.array(z.string()).default([]),
  city_ids: z.array(z.string()).default([]),
  keyword_ids: z.array(z.string()).default([]),
  sector_ids: z.array(z.string()).default([]),
  state_ids: z.array(z.string()).default([]),
  meta_title: z.string().default(""),
  meta_description: z.string().default(""),
  meta_keywords: z.string().default(""),
});
