import { z } from "zod";

export const TenderSchema = z.object({
  name: z.string().default(""),
  tender_amount: z.number().int().default(0),
  bid_start_date: z.coerce.date(),
  bid_end_date: z.coerce.date(),
  bid_number: z.string().default(""),
  dated: z.string().default(""),
  bid_end_date_time: z.string().default(""),
  department: z.string().default(""),
  organisation: z.string().default(""),
  office: z.string().default(""),
  item_gem_parts: z.string().default(""),
  quantity: z.string().default(""),
  uom: z.string().default(""),
  no_of_items: z.string().default(""),
  minimum_average_annual_turnover: z.string().default(""),
  years_of_past_experience: z.string().default(""),
  evaluation_method: z.string().default(""),
  emd_amount: z.string().default(""),
  tender_value: z.string().default(""),
  ote_lte: z.string().default(""),
  epbg_percentage: z.string().default(""),
  buyer_specification_document: z.string().default(""),
  drawing: z.string().default(""),
  consignee: z.string().default(""),
  delivery_days: z.string().default(""),
  distribution: z.string().default(""),
  pre_qualification_criteria: z.string().default(""),
  mse_exemption_for_turnover: z.string().default(""),
  startup_exemption_for_turnover: z.string().default(""),
  bid_to_ra_enabled: z.string().default(""),
  splitting_applied: z.string().default(""),
  save_to_my_business: z.string().default(""),
  authority_ids: z.array(z.string()).default([]),
  city_ids: z.array(z.string()).default([]),
  keyword_ids: z.array(z.string()).default([]),
  sector_ids: z.array(z.string()).default([]),
  state_ids: z.array(z.string()).default([]),
  meta_title: z.string().default(""),
  meta_description: z.string().default(""),
  meta_keywords: z.string().default(""),
});
