export const endpoints = {
  profile: "/users/me",
  auth: {
    login: "/auth/login",
    loginRequest: "/auth/login-request",
    loginVerify: "/auth/login-verify",
    regsiterRequest: "/auth/register-request",
    regsiterVerify: "/auth/register-verify",
    refresh: "/auth/refresh",
    username: "/auth/username",
  },
  tenders: {
    getAll: "/tenders",
    getBySlug: "/tenders/get-by-slug",
    favourite: "/wishlists",
  },
  keywords: { getAll: "/keywords" },
  industries: { getAll: "/industries" },
  states: { getAll: "/states" },
  cities: { getAll: "/cities", getByStateIds: "/cities/get-by-state-ids" },
  sectors: { getAll: "/sectors" },
  authorities: { getAll: "/authorities" },
  wishlists: { getAll: "/wishlists" },
  companyProfiles: { getAll: "/company-profiles" },
  userKeyContacts: { getAll: "/user-key-contacts" },
  viewTenders: { getAll: "/view-tenders" },
  applications: { getAll: "/applications" },
  inquiries: { getAll: "/inquiries" },
  preferences: { getAll: "/preferences" },
  plans: { getAll: "/plans" },
  subscriptions: { getAll: "/subscriptions" },
  categories: { getAll: "/categories" },
  payments: { getAll: "/payments" },
  subcategories: {
    getAll: "/sub-categories",
    getByCategory: "/sub-categories/get-by-category",
  },
  files: {
    getFiles: "/upload",
    deleteKey: "/upload/s3",
    preSignedUrl: "/upload/presigned-url",
    preSignedUrls: "/upload/presigned-urls",
  },
};
