export const endpoints = {
  auth: {
    login: "/auth/login",
    signup: "/auth/signup",
    refresh: "/auth/refresh",
    username: "/auth/username",
  },
  tenders: {
    getAll: "/tenders",
    getBySlug: "/tenders/get-by-slug",
    favourite: "/wishlists",
  },
  keywords: { getAll: "/keywords" },
  states: { getAll: "/states" },
  cities: { getAll: "/cities" },
  sectors: { getAll: "/sectors" },
  authorities: { getAll: "/authorities" },
  wishlists: { getAll: "/wishlists" },
  companyProfiles: { getAll: "/company-profiles" },
  userKeyContacts: { getAll: "/user-key-contacts" },
  viewTenders: { getAll: "/view-tenders" },
  applications: { getAll: "/applications" },
  profile: "/users/me",
  files: {
    getFiles: "/upload",
    deleteKey: "/upload/s3",
    preSignedUrl: "/upload/presigned-url",
    preSignedUrls: "/upload/presigned-urls",
  },
};
